server:
  servlet:
    context-path: /
    session:
      timeout: 1800m
  port: 8888
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      WRITE_NUMBERS_AS_STRINGS: true
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  redis:
    host: 127.0.0.1
    port: 6379
    password: mkt2China
  devtools:
      restart:
        enabled: true
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: com.yige.**.domain
  global-config:
    id-type: 2
    field-strategy: 1
    db-column-underline: false
    #是否开启大写命名
    capital-mode: false
    #自定义 SQL 注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    logic-not-delete-value: 0
    logic-delete-value: 1
  configuration:
    #开启驼峰
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


